baseURL = "https:thegopieffect.github.io/"
languageCode = "en-us"
title = "My Ramble"
theme = "dream"

# These are from dream quickstart guide
defaultContentLanguage = "en"
googleAnalytics = "..."
disqusShortname = "thegopieffect"
enableRobotsTXT = true


